# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7f4b161d9d42b0b33e269db079b92330"
name = "stripe-maya-api"
handle = "stripe-maya-api-1"
application_url = "https://signature-florence-spin-oaks.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-aa1e7864.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://vitamin-harassment-recorders-lightning.trycloudflare.com/auth/callback",
  "https://vitamin-harassment-recorders-lightning.trycloudflare.com/auth/shopify/callback",
  "https://vitamin-harassment-recorders-lightning.trycloudflare.com/api/auth/callback",
  "https://suit-php-providing-junior.trycloudflare.com/auth/callback",
  "https://suit-php-providing-junior.trycloudflare.com/auth/shopify/callback",
  "https://suit-php-providing-junior.trycloudflare.com/api/auth/callback",
  "https://blink-fine-brochures-houses.trycloudflare.com/auth/callback",
  "https://blink-fine-brochures-houses.trycloudflare.com/auth/shopify/callback",
  "https://blink-fine-brochures-houses.trycloudflare.com/api/auth/callback",
  "https://joe-advisors-devices-encounter.trycloudflare.com/auth/callback",
  "https://joe-advisors-devices-encounter.trycloudflare.com/auth/shopify/callback",
  "https://joe-advisors-devices-encounter.trycloudflare.com/api/auth/callback",
  "https://adverse-telescope-ons-interval.trycloudflare.com/auth/callback",
  "https://adverse-telescope-ons-interval.trycloudflare.com/auth/shopify/callback",
  "https://adverse-telescope-ons-interval.trycloudflare.com/api/auth/callback",
  "https://solutions-outcome-wherever-bottle.trycloudflare.com/auth/callback",
  "https://solutions-outcome-wherever-bottle.trycloudflare.com/auth/shopify/callback",
  "https://solutions-outcome-wherever-bottle.trycloudflare.com/api/auth/callback",
  "https://teacher-impressive-experience-es.trycloudflare.com/auth/callback",
  "https://teacher-impressive-experience-es.trycloudflare.com/auth/shopify/callback",
  "https://teacher-impressive-experience-es.trycloudflare.com/api/auth/callback",
  "https://chapter-addresses-confirmed-kiss.trycloudflare.com/auth/callback",
  "https://chapter-addresses-confirmed-kiss.trycloudflare.com/auth/shopify/callback",
  "https://chapter-addresses-confirmed-kiss.trycloudflare.com/api/auth/callback",
  "https://coast-bi-forgot-europe.trycloudflare.com/auth/callback",
  "https://coast-bi-forgot-europe.trycloudflare.com/auth/shopify/callback",
  "https://coast-bi-forgot-europe.trycloudflare.com/api/auth/callback",
  "https://copying-ronald-autumn-goat.trycloudflare.com/auth/callback",
  "https://copying-ronald-autumn-goat.trycloudflare.com/auth/shopify/callback",
  "https://copying-ronald-autumn-goat.trycloudflare.com/api/auth/callback",
  "https://processing-triumph-sending-urban.trycloudflare.com/auth/callback",
  "https://processing-triumph-sending-urban.trycloudflare.com/auth/shopify/callback",
  "https://processing-triumph-sending-urban.trycloudflare.com/api/auth/callback",
  "https://indices-constitute-intention-reprints.trycloudflare.com/auth/callback",
  "https://indices-constitute-intention-reprints.trycloudflare.com/auth/shopify/callback",
  "https://indices-constitute-intention-reprints.trycloudflare.com/api/auth/callback",
  "https://ten-scholarship-failed-forces.trycloudflare.com/auth/callback",
  "https://ten-scholarship-failed-forces.trycloudflare.com/auth/shopify/callback",
  "https://ten-scholarship-failed-forces.trycloudflare.com/api/auth/callback",
  "https://gulf-ids-said-lp.trycloudflare.com/auth/callback",
  "https://gulf-ids-said-lp.trycloudflare.com/auth/shopify/callback",
  "https://gulf-ids-said-lp.trycloudflare.com/api/auth/callback",
  "https://rewards-drinking-temporary-due.trycloudflare.com/auth/callback",
  "https://rewards-drinking-temporary-due.trycloudflare.com/auth/shopify/callback",
  "https://rewards-drinking-temporary-due.trycloudflare.com/api/auth/callback",
  "https://intake-walking-monitor-ak.trycloudflare.com/auth/callback",
  "https://intake-walking-monitor-ak.trycloudflare.com/auth/shopify/callback",
  "https://intake-walking-monitor-ak.trycloudflare.com/api/auth/callback",
  "https://syntax-sas-processor-icon.trycloudflare.com/auth/callback",
  "https://syntax-sas-processor-icon.trycloudflare.com/auth/shopify/callback",
  "https://syntax-sas-processor-icon.trycloudflare.com/api/auth/callback",
  "https://screen-hb-campaigns-contractors.trycloudflare.com/auth/callback",
  "https://screen-hb-campaigns-contractors.trycloudflare.com/auth/shopify/callback",
  "https://screen-hb-campaigns-contractors.trycloudflare.com/api/auth/callback",
  "https://captured-accessories-undergraduate-demonstration.trycloudflare.com/auth/callback",
  "https://captured-accessories-undergraduate-demonstration.trycloudflare.com/auth/shopify/callback",
  "https://captured-accessories-undergraduate-demonstration.trycloudflare.com/api/auth/callback",
  "https://transmission-vital-iowa-contents.trycloudflare.com/auth/callback",
  "https://transmission-vital-iowa-contents.trycloudflare.com/auth/shopify/callback",
  "https://transmission-vital-iowa-contents.trycloudflare.com/api/auth/callback",
  "https://arrived-robust-signatures-volume.trycloudflare.com/auth/callback",
  "https://arrived-robust-signatures-volume.trycloudflare.com/auth/shopify/callback",
  "https://arrived-robust-signatures-volume.trycloudflare.com/api/auth/callback",
  "https://mainly-currencies-latest-lender.trycloudflare.com/auth/callback",
  "https://mainly-currencies-latest-lender.trycloudflare.com/auth/shopify/callback",
  "https://mainly-currencies-latest-lender.trycloudflare.com/api/auth/callback",
  "https://obtain-hunter-grass-aggressive.trycloudflare.com/auth/callback",
  "https://obtain-hunter-grass-aggressive.trycloudflare.com/auth/shopify/callback",
  "https://obtain-hunter-grass-aggressive.trycloudflare.com/api/auth/callback",
  "https://heaven-salmon-reviews-museums.trycloudflare.com/auth/callback",
  "https://heaven-salmon-reviews-museums.trycloudflare.com/auth/shopify/callback",
  "https://heaven-salmon-reviews-museums.trycloudflare.com/api/auth/callback",
  "https://nicole-mrna-sports-greetings.trycloudflare.com/auth/callback",
  "https://nicole-mrna-sports-greetings.trycloudflare.com/auth/shopify/callback",
  "https://nicole-mrna-sports-greetings.trycloudflare.com/api/auth/callback",
  "https://aw-indie-hs-hints.trycloudflare.com/auth/callback",
  "https://aw-indie-hs-hints.trycloudflare.com/auth/shopify/callback",
  "https://aw-indie-hs-hints.trycloudflare.com/api/auth/callback",
  "https://additionally-suspension-railroad-mba.trycloudflare.com/auth/callback",
  "https://additionally-suspension-railroad-mba.trycloudflare.com/auth/shopify/callback",
  "https://additionally-suspension-railroad-mba.trycloudflare.com/api/auth/callback",
  "https://employer-deferred-platinum-pleasure.trycloudflare.com/auth/callback",
  "https://employer-deferred-platinum-pleasure.trycloudflare.com/auth/shopify/callback",
  "https://employer-deferred-platinum-pleasure.trycloudflare.com/api/auth/callback",
  "https://motorola-reservations-phase-dayton.trycloudflare.com/auth/callback",
  "https://motorola-reservations-phase-dayton.trycloudflare.com/auth/shopify/callback",
  "https://motorola-reservations-phase-dayton.trycloudflare.com/api/auth/callback",
  "https://cube-energy-designation-wanted.trycloudflare.com/auth/callback",
  "https://cube-energy-designation-wanted.trycloudflare.com/auth/shopify/callback",
  "https://cube-energy-designation-wanted.trycloudflare.com/api/auth/callback",
  "https://statewide-suites-command-addition.trycloudflare.com/auth/callback",
  "https://statewide-suites-command-addition.trycloudflare.com/auth/shopify/callback",
  "https://statewide-suites-command-addition.trycloudflare.com/api/auth/callback",
  "https://hiking-expense-jacob-geographical.trycloudflare.com/auth/callback",
  "https://hiking-expense-jacob-geographical.trycloudflare.com/auth/shopify/callback",
  "https://hiking-expense-jacob-geographical.trycloudflare.com/api/auth/callback",
  "https://ghost-modelling-peer-serving.trycloudflare.com/auth/callback",
  "https://ghost-modelling-peer-serving.trycloudflare.com/auth/shopify/callback",
  "https://ghost-modelling-peer-serving.trycloudflare.com/api/auth/callback",
  "https://games-leader-retreat-tide.trycloudflare.com/auth/callback",
  "https://games-leader-retreat-tide.trycloudflare.com/auth/shopify/callback",
  "https://games-leader-retreat-tide.trycloudflare.com/api/auth/callback",
  "https://scotia-shipping-protest-agenda.trycloudflare.com/auth/callback",
  "https://scotia-shipping-protest-agenda.trycloudflare.com/auth/shopify/callback",
  "https://scotia-shipping-protest-agenda.trycloudflare.com/api/auth/callback",
  "https://gratuit-shield-exit-boxes.trycloudflare.com/auth/callback",
  "https://gratuit-shield-exit-boxes.trycloudflare.com/auth/shopify/callback",
  "https://gratuit-shield-exit-boxes.trycloudflare.com/api/auth/callback",
  "https://pale-mustang-destinations-dvd.trycloudflare.com/auth/callback",
  "https://pale-mustang-destinations-dvd.trycloudflare.com/auth/shopify/callback",
  "https://pale-mustang-destinations-dvd.trycloudflare.com/api/auth/callback",
  "https://see-springfield-sbjct-picks.trycloudflare.com/auth/callback",
  "https://see-springfield-sbjct-picks.trycloudflare.com/auth/shopify/callback",
  "https://see-springfield-sbjct-picks.trycloudflare.com/api/auth/callback",
  "https://actively-workflow-titanium-aaa.trycloudflare.com/auth/callback",
  "https://actively-workflow-titanium-aaa.trycloudflare.com/auth/shopify/callback",
  "https://actively-workflow-titanium-aaa.trycloudflare.com/api/auth/callback",
  "https://prevent-gardens-eminem-editions.trycloudflare.com/auth/callback",
  "https://prevent-gardens-eminem-editions.trycloudflare.com/auth/shopify/callback",
  "https://prevent-gardens-eminem-editions.trycloudflare.com/api/auth/callback",
  "https://african-grants-debug-apparel.trycloudflare.com/auth/callback",
  "https://african-grants-debug-apparel.trycloudflare.com/auth/shopify/callback",
  "https://african-grants-debug-apparel.trycloudflare.com/api/auth/callback",
  "https://composite-assuming-ear-expressed.trycloudflare.com/auth/callback",
  "https://composite-assuming-ear-expressed.trycloudflare.com/auth/shopify/callback",
  "https://composite-assuming-ear-expressed.trycloudflare.com/api/auth/callback",
  "https://stephen-retailers-own-accessed.trycloudflare.com/auth/callback",
  "https://stephen-retailers-own-accessed.trycloudflare.com/auth/shopify/callback",
  "https://stephen-retailers-own-accessed.trycloudflare.com/api/auth/callback",
  "https://polls-amendment-stages-silly.trycloudflare.com/auth/callback",
  "https://polls-amendment-stages-silly.trycloudflare.com/auth/shopify/callback",
  "https://polls-amendment-stages-silly.trycloudflare.com/api/auth/callback",
  "https://keeping-tumor-join-either.trycloudflare.com/auth/callback",
  "https://keeping-tumor-join-either.trycloudflare.com/auth/shopify/callback",
  "https://keeping-tumor-join-either.trycloudflare.com/api/auth/callback",
  "https://lots-whom-containing-babies.trycloudflare.com/auth/callback",
  "https://lots-whom-containing-babies.trycloudflare.com/auth/shopify/callback",
  "https://lots-whom-containing-babies.trycloudflare.com/api/auth/callback",
  "https://feb-goals-public-museum.trycloudflare.com/auth/callback",
  "https://feb-goals-public-museum.trycloudflare.com/auth/shopify/callback",
  "https://feb-goals-public-museum.trycloudflare.com/api/auth/callback",
  "https://casa-duty-appreciate-scored.trycloudflare.com/auth/callback",
  "https://casa-duty-appreciate-scored.trycloudflare.com/auth/shopify/callback",
  "https://casa-duty-appreciate-scored.trycloudflare.com/api/auth/callback",
  "https://computed-appointment-records-ips.trycloudflare.com/auth/callback",
  "https://computed-appointment-records-ips.trycloudflare.com/auth/shopify/callback",
  "https://computed-appointment-records-ips.trycloudflare.com/api/auth/callback",
  "https://pamela-networks-seminar-accident.trycloudflare.com/auth/callback",
  "https://pamela-networks-seminar-accident.trycloudflare.com/auth/shopify/callback",
  "https://pamela-networks-seminar-accident.trycloudflare.com/api/auth/callback",
  "https://nav-reef-hamilton-routing.trycloudflare.com/auth/callback",
  "https://nav-reef-hamilton-routing.trycloudflare.com/auth/shopify/callback",
  "https://nav-reef-hamilton-routing.trycloudflare.com/api/auth/callback",
  "https://spotlight-candidates-know-gs.trycloudflare.com/auth/callback",
  "https://spotlight-candidates-know-gs.trycloudflare.com/auth/shopify/callback",
  "https://spotlight-candidates-know-gs.trycloudflare.com/api/auth/callback",
  "https://trick-multimedia-surely-stay.trycloudflare.com/auth/callback",
  "https://trick-multimedia-surely-stay.trycloudflare.com/auth/shopify/callback",
  "https://trick-multimedia-surely-stay.trycloudflare.com/api/auth/callback",
  "https://guilty-scientific-paint-atom.trycloudflare.com/auth/callback",
  "https://guilty-scientific-paint-atom.trycloudflare.com/auth/shopify/callback",
  "https://guilty-scientific-paint-atom.trycloudflare.com/api/auth/callback",
  "https://mauritius-harder-showed-gains.trycloudflare.com/auth/callback",
  "https://mauritius-harder-showed-gains.trycloudflare.com/auth/shopify/callback",
  "https://mauritius-harder-showed-gains.trycloudflare.com/api/auth/callback",
  "https://always-intelligence-witness-exhaust.trycloudflare.com/auth/callback",
  "https://always-intelligence-witness-exhaust.trycloudflare.com/auth/shopify/callback",
  "https://always-intelligence-witness-exhaust.trycloudflare.com/api/auth/callback",
  "https://enrollment-clone-baghdad-impressed.trycloudflare.com/auth/callback",
  "https://enrollment-clone-baghdad-impressed.trycloudflare.com/auth/shopify/callback",
  "https://enrollment-clone-baghdad-impressed.trycloudflare.com/api/auth/callback",
  "https://beside-prepare-albuquerque-experiment.trycloudflare.com/auth/callback",
  "https://beside-prepare-albuquerque-experiment.trycloudflare.com/auth/shopify/callback",
  "https://beside-prepare-albuquerque-experiment.trycloudflare.com/api/auth/callback",
  "https://falling-les-impacts-abroad.trycloudflare.com/auth/callback",
  "https://falling-les-impacts-abroad.trycloudflare.com/auth/shopify/callback",
  "https://falling-les-impacts-abroad.trycloudflare.com/api/auth/callback",
  "https://standing-starting-following-bet.trycloudflare.com/auth/callback",
  "https://standing-starting-following-bet.trycloudflare.com/auth/shopify/callback",
  "https://standing-starting-following-bet.trycloudflare.com/api/auth/callback",
  "https://ln-au-yr-genesis.trycloudflare.com/auth/callback",
  "https://ln-au-yr-genesis.trycloudflare.com/auth/shopify/callback",
  "https://ln-au-yr-genesis.trycloudflare.com/api/auth/callback",
  "https://tub-chain-cottages-bus.trycloudflare.com/auth/callback",
  "https://tub-chain-cottages-bus.trycloudflare.com/auth/shopify/callback",
  "https://tub-chain-cottages-bus.trycloudflare.com/api/auth/callback",
  "https://signature-florence-spin-oaks.trycloudflare.com/auth/callback",
  "https://signature-florence-spin-oaks.trycloudflare.com/auth/shopify/callback",
  "https://signature-florence-spin-oaks.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
